spring:
  profiles:
    active: dev
---
server:
  port: 8021
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-cloud-atguigu-dev

---
spring:
  profiles: test #开发环境
  application:
    name: microservicecloud-cloud-atguigu-test
#请保存为utf-8格式
