spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-cloud-eureka-client
server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
---
spring:
  profiles: test #开发环境
  application:
    name: microservicecloud-cloud-atguigu-test
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#请保存为utf-8格式
server:
  port: 7001